export const knowledge = {
  empresa: { nombre: "Link Jobs", tagline: "Revolutionizing Youth Talent Acquisition", ubicacion: "Puebla, México", website: "linkjobs.mx", estado: "Desarrollo activo — plataforma ~80% funcional", fundador: "Zair Aquino", correo: "allmadesarrollo@gmail.com", equipo: "Zair Aquino (CEO/Dev) + Dev partner", version_modelo: "v2.0 — Pivote a modelo dual B2B (principal) + B2C (captación de talento)", ultima_actualizacion: "Marzo 2026" },
  problema: { resumen: "México tiene el 54.6% de informalidad laboral y una tasa de rotación del 17% (la más alta de LATAM). Las empresas pierden hasta $200,000 MXN por mala contratación.", dolores_empresas: ["Proceso burocrático interminable: correos, convenios físicos, perfiles desactualizados", "Sin garantía: pagan agencias que cobran 1 mes de salario sin garantizar permanencia", "Rotación del 17% (la más alta de LATAM)", "Hasta $200,000 MXN en costos por mala contratación (fuente: AMEDIRH)"], datos_clave: { informalidad: "54.6%", rotacion_promedio: "17%", costo_rotacion: "hasta $200,000 MXN", estudiantes_superiores: "5,140,535", egresados_por_semestre: "~505,000", jovenes_desempleados_15_29: "843,000+", practicantes_buap_por_anio: "24,000", convenios_buap: "3,382 empresas" } },
  solucion: { descripcion: "Plataforma HR Tech que administra integralmente practicantes para empresas: reclutamiento, convenio universidad-empresa, dispersión de becas, dashboard de seguimiento, facturación deducible, y garantía de reemplazo.", tres_pilares: ["Flexibilidad: el convenio y la plataforma se adaptan a las necesidades de la empresa", "Accesibilidad: esquema de precios (SaaS/Membresía) muy competitivo vs agencias tradicionales", "Resolución Burocrática: facilitamos todo el papeleo universidad-empresa, ahorrando semanas de trámites"], incluye: ["Búsqueda y filtro de candidatos", "Gestión del convenio tripartita", "Dispersión mensual de beca al practicante", "Dashboard de seguimiento y KPIs", "Factura 100% deducible (asimilados a salarios, Art. 94 LISR)", "Garantía de Reemplazo: 15 días hábiles o refund completo"], que_NO_es: "No es una bolsa de trabajo tradicional. No es una agencia de reclutamiento. Es una membresía de administración integral de practicantes." },
  como_funciona: { ciclo: "Semestral (4-6 meses)", fases: [{ fase: "Fase 0 — Constitución", practicantes: 0, actividades: "Constituir SAS, RFC, CFDI, alianza PADLA" }, { fase: "Fase 1 — Primeros clientes", practicantes: "1-6", costos_fijos: "$1,820/mes" }, { fase: "Fase 2 — Tracción", practicantes: "7-14", salario_zair: "$4,000" }, { fase: "Fase 3 — Estabilidad", practicantes: "15-24" }, { fase: "Fase 4 — Crecimiento", practicantes: "25+" }], timeline: [{ periodo: "Mes 1-2", meta: "Constitución SAS + alianza PADLA", ingresos: "$0" }, { periodo: "Mes 3", meta: "3-5 practicantes", ingresos: "$4K-$7K" }, { periodo: "Mes 4-5", meta: "6-9 practicantes", ingresos: "$8K-$12K" }, { periodo: "Mes 9-12", meta: "20-25 practicantes", ingresos: "$27K-$34K" }] },
  precios: {
    modelo_piloto: { descripcion: "Fee de administración directo (modelo por practicante)", fee_perfil_nuevo: { monto: 1350, moneda: "MXN", frecuencia: "One-time al dar de alta" }, fee_administracion_mensual: { monto: 1350, moneda: "MXN", frecuencia: "Mensual recurrente" }, total_mes_1_por_practicante: 2700, total_meses_siguientes: 1350, punto_equilibrio: "5 practicantes activos" },
    planes_B2B_membresia: { planes: [{ nombre: "LinkJobs+ (Starter)", precio: 32500, moneda: "MXN", periodo: "por ciclo semestral", practicantes: "1-2", incluye: ["Resolución burocrática completa", "Perfilado y match de candidatos", "Workspace Digital", "Eventos bienvenida y finalización", "Reporte final"] }, { nombre: "Core Team (Growth)", precio: 90000, moneda: "MXN", periodo: "por ciclo semestral", practicantes: "3", incluye: ["Todo de Starter", "Kit físico", "Eventos de comunidad mensuales"] }, { nombre: "Enterprise (Scale)", precio: 170000, moneda: "MXN", periodo: "por ciclo semestral", practicantes: "4-6", incluye: ["Todo de Growth", "Kit con licencias", "5 eventos mensuales", "Dashboard avanzado"] }, { nombre: "Enterprise Plus", precio: "A la medida", practicantes: "Personalizado", incluye: ["Todo de Enterprise", "Resolución burocrática internacional"] }], ticket_promedio_ponderado: 72500 }
  },
  roi: { resumen: "LinkJobs genera ROI positivo eliminando costos ocultos del empleo formal (IMSS, INFONAVIT, SAR, aguinaldo, vacaciones).", ahorro_vs_empleado_formal: { ejemplo_beca_7000: { costo_bruto_empleado_formal: 10325, costo_bruto_con_linkjobs: 8350, ahorro_neto_mes: 1382 }, ahorro_anual_10_practicantes: 165840 }, roi_porcentaje: "46% - 205%", ltv_estimado: 348000, cac_estimado: "5,000 - 15,000 MXN", ratio_ltv_cac: "23x - 70x", deducibilidad: { mecanismo: "Asimilados a salarios (Art. 94 LISR)", imss_patronal: "$0", infonavit: "$0", sar: "$0" } },
  mercado: { tam: { empresas: 257004, descripcion: "Todas las empresas con 11+ empleados en México", valor_semestral: "18,632 millones MXN" }, sam: { empresas: 25700, descripcion: "Empresas con programas de prácticas activos (10% del TAM)" }, hr_tech_mexico: { valor_2024: "540M USD", cagr: "7.7%", valor_2033: "1,050M USD" }, puebla_especifico: { pymes_11_250: "~10,300", grandes_250_mas: "~370", empresas_clave: "AUDI, VW, Hershey, Tyson + startups tech", competencia_local: "NINGUN competidor con presencia local en administración de practicantes" }, competidores: { caintra: { sede: "Monterrey", practicantes_anio: 30000, en_puebla: "Solo remoto" }, becarios_mx: { sede: "Monterrey", en_puebla: "Solo remoto" } } },
  testimonios: [{ persona: "Ivonne Huerta Almaraz", cargo: "Dueña / Directora", empresa: "Padla Universitas", cita: "Validamos la importancia de contar con una bolsa activa y reconocemos el valor masivo de simplificar el papeleo entre las universidades y las empresas.", status: "Alianza en negociación" }, { persona: "Daniela", cargo: "Encargada de RRHH", empresa: "KIGO", cita: "El rango de precios $65K-$85K considerado muy barato frente a sus costos actuales." }, { persona: "Carlos Anaya Rodriguez", cargo: "CEO & Fundador", empresa: "KIGO", cita: "Proyecto con mucho potencial.", status: "Demo pendiente" }],
  marketing: { post_linkedin: "LinkJobs esta llegando a Puebla y vamos a cambiar como las empresas contratan talento joven.", propuesta_valor_b2b: "Reducimos hasta un 40% el tiempo burocrático de contratación de practicantes.", propuesta_valor_b2c: "Aplica a más trabajos en menos tiempo con IA. CV personalizado por $649 MXN.", colores: { primario: "#1E3A5F", secundario: "#F5A623", tipografia: "Inter / Geist" } },
  estado_actual: { plataforma: { estado: "~80% funcional", paginas_completadas: ["index", "vacantes", "portal", "promo", "checkout"], integraciones: ["Stripe", "Clarity", "UTM tracking"] }, legal: { figura: "SAS", estado: "Pendiente de constitución" }, metricas: { prospectos_corporativos: 3, reuniones_realizadas: 1, convenios_firmados: 0, ingresos_generados: 0 }, tareas_pendientes: [{ tarea: "Completar plataforma", prioridad: "alta" }, { tarea: "Demo para KIGO", prioridad: "alta" }, { tarea: "Alianza con PADLA", prioridad: "alta" }, { tarea: "Cerrar primer convenio corporativo", prioridad: "alta" }] }
};

export function buscarEnKnowledge(query) {
  const q = query.toLowerCase();
  const resultados = [];
  function buscarEnObjeto(obj, ruta) {
    if (!ruta) ruta = "";
    if (typeof obj === "string") { if (obj.toLowerCase().includes(q)) resultados.push({ ruta, fragmento: obj.substring(0, 200) }); }
    else if (Array.isArray(obj)) obj.forEach((item, i) => buscarEnObjeto(item, ruta + "[" + i + "]"));
    else if (typeof obj === "object" && obj !== null) Object.entries(obj).forEach(([key, val]) => buscarEnObjeto(val, ruta ? ruta + "." + key : key));
  }
  buscarEnObjeto(knowledge);
  return resultados.slice(0, 10);
}
